name: irav
favicon: null
layout_spectrum: 0.92571
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c3d3f'
    - '#060606'
    - '#6e6f73'
    - '#f0ded3'
    - '#a38778'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
